### ISSUE TITLE
workout time showing on app isn't correct.

### ISSUE THREAD

**Issue by beaudamion** [Rexios80/hds_overlay#64]
Hardware/Software

iPhone: 13 Pro
iOS: 16.0.2
Apple Watch: Series 5 44mm
watchOS: 9.0
Windows: Windows 10 Pro 21H2 19044
App: 13.0 (1)

To Reproduce
The running clock for the workout doesn't show the right time (how long it's been running). I think when the screen goes to the non refreshed "always-on / dimmed" look the time stops updating.. once you look down at the watch again it just updates where it left off... over an hour workout will show like 28 minutes on the app.

**Comment by Rexios80** [comment]
This should already be fixed on TestFlight: https://testflight.apple.com/join/hG4FkmZ4

**Comment by Rexios80** [comment]
Wait you already have 13.0 from TestFlight?

**Comment by beaudamion** [comment]
yeah I'm already on that version.

**Comment by Rexios80** [comment]
Hmmm yeah it was a problem but I thought I fixed it. Let me check.

**Comment by Rexios80** [comment]
This should now actually be fixed in the TestFlight version 🙃

**Comment by beaudamion** [comment]
(｡◕‿‿◕｡)
